// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nfsfuse.proto

#ifndef PROTOBUF_nfsfuse_2eproto__INCLUDED
#define PROTOBUF_nfsfuse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace nfsfuse {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_nfsfuse_2eproto();
void protobuf_AssignDesc_nfsfuse_2eproto();
void protobuf_ShutdownFile_nfsfuse_2eproto();

class Dirent;
class FuseFileInfo;
class Mkdir;
class MkdirOutput;
class ReadRequest;
class ReadResult;
class SerializeByte;
class Stat;
class String;
class WriteRequest;
class WriteResult;

// ===================================================================

class SerializeByte : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nfsfuse.SerializeByte) */ {
 public:
  SerializeByte();
  virtual ~SerializeByte();

  SerializeByte(const SerializeByte& from);

  inline SerializeByte& operator=(const SerializeByte& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SerializeByte& default_instance();

  void Swap(SerializeByte* other);

  // implements Message ----------------------------------------------

  inline SerializeByte* New() const { return New(NULL); }

  SerializeByte* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SerializeByte& from);
  void MergeFrom(const SerializeByte& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SerializeByte* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes buffer = 1;
  void clear_buffer();
  static const int kBufferFieldNumber = 1;
  const ::std::string& buffer() const;
  void set_buffer(const ::std::string& value);
  void set_buffer(const char* value);
  void set_buffer(const void* value, size_t size);
  ::std::string* mutable_buffer();
  ::std::string* release_buffer();
  void set_allocated_buffer(::std::string* buffer);

  // @@protoc_insertion_point(class_scope:nfsfuse.SerializeByte)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr buffer_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_nfsfuse_2eproto();
  friend void protobuf_AssignDesc_nfsfuse_2eproto();
  friend void protobuf_ShutdownFile_nfsfuse_2eproto();

  void InitAsDefaultInstance();
  static SerializeByte* default_instance_;
};
// -------------------------------------------------------------------

class String : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nfsfuse.String) */ {
 public:
  String();
  virtual ~String();

  String(const String& from);

  inline String& operator=(const String& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const String& default_instance();

  void Swap(String* other);

  // implements Message ----------------------------------------------

  inline String* New() const { return New(NULL); }

  String* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const String& from);
  void MergeFrom(const String& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(String* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string str = 1;
  void clear_str();
  static const int kStrFieldNumber = 1;
  const ::std::string& str() const;
  void set_str(const ::std::string& value);
  void set_str(const char* value);
  void set_str(const char* value, size_t size);
  ::std::string* mutable_str();
  ::std::string* release_str();
  void set_allocated_str(::std::string* str);

  // @@protoc_insertion_point(class_scope:nfsfuse.String)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr str_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_nfsfuse_2eproto();
  friend void protobuf_AssignDesc_nfsfuse_2eproto();
  friend void protobuf_ShutdownFile_nfsfuse_2eproto();

  void InitAsDefaultInstance();
  static String* default_instance_;
};
// -------------------------------------------------------------------

class Dirent : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nfsfuse.Dirent) */ {
 public:
  Dirent();
  virtual ~Dirent();

  Dirent(const Dirent& from);

  inline Dirent& operator=(const Dirent& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Dirent& default_instance();

  void Swap(Dirent* other);

  // implements Message ----------------------------------------------

  inline Dirent* New() const { return New(NULL); }

  Dirent* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Dirent& from);
  void MergeFrom(const Dirent& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Dirent* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 dino = 1;
  void clear_dino();
  static const int kDinoFieldNumber = 1;
  ::google::protobuf::uint32 dino() const;
  void set_dino(::google::protobuf::uint32 value);

  // optional string dname = 2;
  void clear_dname();
  static const int kDnameFieldNumber = 2;
  const ::std::string& dname() const;
  void set_dname(const ::std::string& value);
  void set_dname(const char* value);
  void set_dname(const char* value, size_t size);
  ::std::string* mutable_dname();
  ::std::string* release_dname();
  void set_allocated_dname(::std::string* dname);

  // optional uint32 dtype = 3;
  void clear_dtype();
  static const int kDtypeFieldNumber = 3;
  ::google::protobuf::uint32 dtype() const;
  void set_dtype(::google::protobuf::uint32 value);

  // optional uint32 err = 4;
  void clear_err();
  static const int kErrFieldNumber = 4;
  ::google::protobuf::uint32 err() const;
  void set_err(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:nfsfuse.Dirent)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr dname_;
  ::google::protobuf::uint32 dino_;
  ::google::protobuf::uint32 dtype_;
  ::google::protobuf::uint32 err_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_nfsfuse_2eproto();
  friend void protobuf_AssignDesc_nfsfuse_2eproto();
  friend void protobuf_ShutdownFile_nfsfuse_2eproto();

  void InitAsDefaultInstance();
  static Dirent* default_instance_;
};
// -------------------------------------------------------------------

class Stat : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nfsfuse.Stat) */ {
 public:
  Stat();
  virtual ~Stat();

  Stat(const Stat& from);

  inline Stat& operator=(const Stat& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Stat& default_instance();

  void Swap(Stat* other);

  // implements Message ----------------------------------------------

  inline Stat* New() const { return New(NULL); }

  Stat* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Stat& from);
  void MergeFrom(const Stat& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Stat* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 dev = 1;
  void clear_dev();
  static const int kDevFieldNumber = 1;
  ::google::protobuf::uint32 dev() const;
  void set_dev(::google::protobuf::uint32 value);

  // optional uint32 ino = 2;
  void clear_ino();
  static const int kInoFieldNumber = 2;
  ::google::protobuf::uint32 ino() const;
  void set_ino(::google::protobuf::uint32 value);

  // optional uint32 mode = 3;
  void clear_mode();
  static const int kModeFieldNumber = 3;
  ::google::protobuf::uint32 mode() const;
  void set_mode(::google::protobuf::uint32 value);

  // optional uint32 nlink = 4;
  void clear_nlink();
  static const int kNlinkFieldNumber = 4;
  ::google::protobuf::uint32 nlink() const;
  void set_nlink(::google::protobuf::uint32 value);

  // optional uint32 uid = 5;
  void clear_uid();
  static const int kUidFieldNumber = 5;
  ::google::protobuf::uint32 uid() const;
  void set_uid(::google::protobuf::uint32 value);

  // optional uint32 gid = 6;
  void clear_gid();
  static const int kGidFieldNumber = 6;
  ::google::protobuf::uint32 gid() const;
  void set_gid(::google::protobuf::uint32 value);

  // optional sint64 size = 7;
  void clear_size();
  static const int kSizeFieldNumber = 7;
  ::google::protobuf::int64 size() const;
  void set_size(::google::protobuf::int64 value);

  // optional sint64 blksize = 8;
  void clear_blksize();
  static const int kBlksizeFieldNumber = 8;
  ::google::protobuf::int64 blksize() const;
  void set_blksize(::google::protobuf::int64 value);

  // optional sint64 blocks = 9;
  void clear_blocks();
  static const int kBlocksFieldNumber = 9;
  ::google::protobuf::int64 blocks() const;
  void set_blocks(::google::protobuf::int64 value);

  // optional uint32 atime = 10;
  void clear_atime();
  static const int kAtimeFieldNumber = 10;
  ::google::protobuf::uint32 atime() const;
  void set_atime(::google::protobuf::uint32 value);

  // optional uint32 mtime = 11;
  void clear_mtime();
  static const int kMtimeFieldNumber = 11;
  ::google::protobuf::uint32 mtime() const;
  void set_mtime(::google::protobuf::uint32 value);

  // optional uint32 ctime = 12;
  void clear_ctime();
  static const int kCtimeFieldNumber = 12;
  ::google::protobuf::uint32 ctime() const;
  void set_ctime(::google::protobuf::uint32 value);

  // optional uint32 err = 14;
  void clear_err();
  static const int kErrFieldNumber = 14;
  ::google::protobuf::uint32 err() const;
  void set_err(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:nfsfuse.Stat)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 dev_;
  ::google::protobuf::uint32 ino_;
  ::google::protobuf::uint32 mode_;
  ::google::protobuf::uint32 nlink_;
  ::google::protobuf::uint32 uid_;
  ::google::protobuf::uint32 gid_;
  ::google::protobuf::int64 size_;
  ::google::protobuf::int64 blksize_;
  ::google::protobuf::int64 blocks_;
  ::google::protobuf::uint32 atime_;
  ::google::protobuf::uint32 mtime_;
  ::google::protobuf::uint32 ctime_;
  ::google::protobuf::uint32 err_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_nfsfuse_2eproto();
  friend void protobuf_AssignDesc_nfsfuse_2eproto();
  friend void protobuf_ShutdownFile_nfsfuse_2eproto();

  void InitAsDefaultInstance();
  static Stat* default_instance_;
};
// -------------------------------------------------------------------

class FuseFileInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nfsfuse.FuseFileInfo) */ {
 public:
  FuseFileInfo();
  virtual ~FuseFileInfo();

  FuseFileInfo(const FuseFileInfo& from);

  inline FuseFileInfo& operator=(const FuseFileInfo& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FuseFileInfo& default_instance();

  void Swap(FuseFileInfo* other);

  // implements Message ----------------------------------------------

  inline FuseFileInfo* New() const { return New(NULL); }

  FuseFileInfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FuseFileInfo& from);
  void MergeFrom(const FuseFileInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(FuseFileInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 flags = 1;
  void clear_flags();
  static const int kFlagsFieldNumber = 1;
  ::google::protobuf::int32 flags() const;
  void set_flags(::google::protobuf::int32 value);

  // optional int32 fh = 2;
  void clear_fh();
  static const int kFhFieldNumber = 2;
  ::google::protobuf::int32 fh() const;
  void set_fh(::google::protobuf::int32 value);

  // optional uint32 oldfh = 3;
  void clear_oldfh();
  static const int kOldfhFieldNumber = 3;
  ::google::protobuf::uint32 oldfh() const;
  void set_oldfh(::google::protobuf::uint32 value);

  // optional uint64 lockowner = 5;
  void clear_lockowner();
  static const int kLockownerFieldNumber = 5;
  ::google::protobuf::uint64 lockowner() const;
  void set_lockowner(::google::protobuf::uint64 value);

  // optional uint32 pollevent = 6;
  void clear_pollevent();
  static const int kPolleventFieldNumber = 6;
  ::google::protobuf::uint32 pollevent() const;
  void set_pollevent(::google::protobuf::uint32 value);

  // optional uint32 err = 4;
  void clear_err();
  static const int kErrFieldNumber = 4;
  ::google::protobuf::uint32 err() const;
  void set_err(::google::protobuf::uint32 value);

  // optional string path = 7;
  void clear_path();
  static const int kPathFieldNumber = 7;
  const ::std::string& path() const;
  void set_path(const ::std::string& value);
  void set_path(const char* value);
  void set_path(const char* value, size_t size);
  ::std::string* mutable_path();
  ::std::string* release_path();
  void set_allocated_path(::std::string* path);

  // @@protoc_insertion_point(class_scope:nfsfuse.FuseFileInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 flags_;
  ::google::protobuf::int32 fh_;
  ::google::protobuf::uint64 lockowner_;
  ::google::protobuf::uint32 oldfh_;
  ::google::protobuf::uint32 pollevent_;
  ::google::protobuf::internal::ArenaStringPtr path_;
  ::google::protobuf::uint32 err_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_nfsfuse_2eproto();
  friend void protobuf_AssignDesc_nfsfuse_2eproto();
  friend void protobuf_ShutdownFile_nfsfuse_2eproto();

  void InitAsDefaultInstance();
  static FuseFileInfo* default_instance_;
};
// -------------------------------------------------------------------

class ReadResult : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nfsfuse.ReadResult) */ {
 public:
  ReadResult();
  virtual ~ReadResult();

  ReadResult(const ReadResult& from);

  inline ReadResult& operator=(const ReadResult& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReadResult& default_instance();

  void Swap(ReadResult* other);

  // implements Message ----------------------------------------------

  inline ReadResult* New() const { return New(NULL); }

  ReadResult* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ReadResult& from);
  void MergeFrom(const ReadResult& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ReadResult* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 bytesread = 1;
  void clear_bytesread();
  static const int kBytesreadFieldNumber = 1;
  ::google::protobuf::int32 bytesread() const;
  void set_bytesread(::google::protobuf::int32 value);

  // optional bytes buffer = 2;
  void clear_buffer();
  static const int kBufferFieldNumber = 2;
  const ::std::string& buffer() const;
  void set_buffer(const ::std::string& value);
  void set_buffer(const char* value);
  void set_buffer(const void* value, size_t size);
  ::std::string* mutable_buffer();
  ::std::string* release_buffer();
  void set_allocated_buffer(::std::string* buffer);

  // @@protoc_insertion_point(class_scope:nfsfuse.ReadResult)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr buffer_;
  ::google::protobuf::int32 bytesread_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_nfsfuse_2eproto();
  friend void protobuf_AssignDesc_nfsfuse_2eproto();
  friend void protobuf_ShutdownFile_nfsfuse_2eproto();

  void InitAsDefaultInstance();
  static ReadResult* default_instance_;
};
// -------------------------------------------------------------------

class ReadRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nfsfuse.ReadRequest) */ {
 public:
  ReadRequest();
  virtual ~ReadRequest();

  ReadRequest(const ReadRequest& from);

  inline ReadRequest& operator=(const ReadRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReadRequest& default_instance();

  void Swap(ReadRequest* other);

  // implements Message ----------------------------------------------

  inline ReadRequest* New() const { return New(NULL); }

  ReadRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ReadRequest& from);
  void MergeFrom(const ReadRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ReadRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string path = 1;
  void clear_path();
  static const int kPathFieldNumber = 1;
  const ::std::string& path() const;
  void set_path(const ::std::string& value);
  void set_path(const char* value);
  void set_path(const char* value, size_t size);
  ::std::string* mutable_path();
  ::std::string* release_path();
  void set_allocated_path(::std::string* path);

  // optional uint32 size = 2;
  void clear_size();
  static const int kSizeFieldNumber = 2;
  ::google::protobuf::uint32 size() const;
  void set_size(::google::protobuf::uint32 value);

  // optional int64 offset = 3;
  void clear_offset();
  static const int kOffsetFieldNumber = 3;
  ::google::protobuf::int64 offset() const;
  void set_offset(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:nfsfuse.ReadRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr path_;
  ::google::protobuf::int64 offset_;
  ::google::protobuf::uint32 size_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_nfsfuse_2eproto();
  friend void protobuf_AssignDesc_nfsfuse_2eproto();
  friend void protobuf_ShutdownFile_nfsfuse_2eproto();

  void InitAsDefaultInstance();
  static ReadRequest* default_instance_;
};
// -------------------------------------------------------------------

class WriteRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nfsfuse.WriteRequest) */ {
 public:
  WriteRequest();
  virtual ~WriteRequest();

  WriteRequest(const WriteRequest& from);

  inline WriteRequest& operator=(const WriteRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WriteRequest& default_instance();

  void Swap(WriteRequest* other);

  // implements Message ----------------------------------------------

  inline WriteRequest* New() const { return New(NULL); }

  WriteRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WriteRequest& from);
  void MergeFrom(const WriteRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(WriteRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string path = 1;
  void clear_path();
  static const int kPathFieldNumber = 1;
  const ::std::string& path() const;
  void set_path(const ::std::string& value);
  void set_path(const char* value);
  void set_path(const char* value, size_t size);
  ::std::string* mutable_path();
  ::std::string* release_path();
  void set_allocated_path(::std::string* path);

  // optional uint32 size = 2;
  void clear_size();
  static const int kSizeFieldNumber = 2;
  ::google::protobuf::uint32 size() const;
  void set_size(::google::protobuf::uint32 value);

  // optional int32 offset = 3;
  void clear_offset();
  static const int kOffsetFieldNumber = 3;
  ::google::protobuf::int32 offset() const;
  void set_offset(::google::protobuf::int32 value);

  // optional bytes buffer = 4;
  void clear_buffer();
  static const int kBufferFieldNumber = 4;
  const ::std::string& buffer() const;
  void set_buffer(const ::std::string& value);
  void set_buffer(const char* value);
  void set_buffer(const void* value, size_t size);
  ::std::string* mutable_buffer();
  ::std::string* release_buffer();
  void set_allocated_buffer(::std::string* buffer);

  // @@protoc_insertion_point(class_scope:nfsfuse.WriteRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr path_;
  ::google::protobuf::uint32 size_;
  ::google::protobuf::int32 offset_;
  ::google::protobuf::internal::ArenaStringPtr buffer_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_nfsfuse_2eproto();
  friend void protobuf_AssignDesc_nfsfuse_2eproto();
  friend void protobuf_ShutdownFile_nfsfuse_2eproto();

  void InitAsDefaultInstance();
  static WriteRequest* default_instance_;
};
// -------------------------------------------------------------------

class WriteResult : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nfsfuse.WriteResult) */ {
 public:
  WriteResult();
  virtual ~WriteResult();

  WriteResult(const WriteResult& from);

  inline WriteResult& operator=(const WriteResult& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WriteResult& default_instance();

  void Swap(WriteResult* other);

  // implements Message ----------------------------------------------

  inline WriteResult* New() const { return New(NULL); }

  WriteResult* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WriteResult& from);
  void MergeFrom(const WriteResult& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(WriteResult* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 nbytes = 1;
  void clear_nbytes();
  static const int kNbytesFieldNumber = 1;
  ::google::protobuf::int32 nbytes() const;
  void set_nbytes(::google::protobuf::int32 value);

  // optional int32 err = 2;
  void clear_err();
  static const int kErrFieldNumber = 2;
  ::google::protobuf::int32 err() const;
  void set_err(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:nfsfuse.WriteResult)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 nbytes_;
  ::google::protobuf::int32 err_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_nfsfuse_2eproto();
  friend void protobuf_AssignDesc_nfsfuse_2eproto();
  friend void protobuf_ShutdownFile_nfsfuse_2eproto();

  void InitAsDefaultInstance();
  static WriteResult* default_instance_;
};
// -------------------------------------------------------------------

class Mkdir : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nfsfuse.Mkdir) */ {
 public:
  Mkdir();
  virtual ~Mkdir();

  Mkdir(const Mkdir& from);

  inline Mkdir& operator=(const Mkdir& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Mkdir& default_instance();

  void Swap(Mkdir* other);

  // implements Message ----------------------------------------------

  inline Mkdir* New() const { return New(NULL); }

  Mkdir* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Mkdir& from);
  void MergeFrom(const Mkdir& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Mkdir* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string s = 1;
  void clear_s();
  static const int kSFieldNumber = 1;
  const ::std::string& s() const;
  void set_s(const ::std::string& value);
  void set_s(const char* value);
  void set_s(const char* value, size_t size);
  ::std::string* mutable_s();
  ::std::string* release_s();
  void set_allocated_s(::std::string* s);

  // optional uint32 mode = 2;
  void clear_mode();
  static const int kModeFieldNumber = 2;
  ::google::protobuf::uint32 mode() const;
  void set_mode(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:nfsfuse.Mkdir)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr s_;
  ::google::protobuf::uint32 mode_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_nfsfuse_2eproto();
  friend void protobuf_AssignDesc_nfsfuse_2eproto();
  friend void protobuf_ShutdownFile_nfsfuse_2eproto();

  void InitAsDefaultInstance();
  static Mkdir* default_instance_;
};
// -------------------------------------------------------------------

class MkdirOutput : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nfsfuse.MkdirOutput) */ {
 public:
  MkdirOutput();
  virtual ~MkdirOutput();

  MkdirOutput(const MkdirOutput& from);

  inline MkdirOutput& operator=(const MkdirOutput& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MkdirOutput& default_instance();

  void Swap(MkdirOutput* other);

  // implements Message ----------------------------------------------

  inline MkdirOutput* New() const { return New(NULL); }

  MkdirOutput* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MkdirOutput& from);
  void MergeFrom(const MkdirOutput& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MkdirOutput* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string str = 1;
  void clear_str();
  static const int kStrFieldNumber = 1;
  const ::std::string& str() const;
  void set_str(const ::std::string& value);
  void set_str(const char* value);
  void set_str(const char* value, size_t size);
  ::std::string* mutable_str();
  ::std::string* release_str();
  void set_allocated_str(::std::string* str);

  // optional uint32 err = 2;
  void clear_err();
  static const int kErrFieldNumber = 2;
  ::google::protobuf::uint32 err() const;
  void set_err(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:nfsfuse.MkdirOutput)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr str_;
  ::google::protobuf::uint32 err_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_nfsfuse_2eproto();
  friend void protobuf_AssignDesc_nfsfuse_2eproto();
  friend void protobuf_ShutdownFile_nfsfuse_2eproto();

  void InitAsDefaultInstance();
  static MkdirOutput* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// SerializeByte

// optional bytes buffer = 1;
inline void SerializeByte::clear_buffer() {
  buffer_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SerializeByte::buffer() const {
  // @@protoc_insertion_point(field_get:nfsfuse.SerializeByte.buffer)
  return buffer_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SerializeByte::set_buffer(const ::std::string& value) {
  
  buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nfsfuse.SerializeByte.buffer)
}
inline void SerializeByte::set_buffer(const char* value) {
  
  buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nfsfuse.SerializeByte.buffer)
}
inline void SerializeByte::set_buffer(const void* value, size_t size) {
  
  buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nfsfuse.SerializeByte.buffer)
}
inline ::std::string* SerializeByte::mutable_buffer() {
  
  // @@protoc_insertion_point(field_mutable:nfsfuse.SerializeByte.buffer)
  return buffer_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SerializeByte::release_buffer() {
  // @@protoc_insertion_point(field_release:nfsfuse.SerializeByte.buffer)
  
  return buffer_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SerializeByte::set_allocated_buffer(::std::string* buffer) {
  if (buffer != NULL) {
    
  } else {
    
  }
  buffer_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), buffer);
  // @@protoc_insertion_point(field_set_allocated:nfsfuse.SerializeByte.buffer)
}

// -------------------------------------------------------------------

// String

// optional string str = 1;
inline void String::clear_str() {
  str_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& String::str() const {
  // @@protoc_insertion_point(field_get:nfsfuse.String.str)
  return str_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void String::set_str(const ::std::string& value) {
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nfsfuse.String.str)
}
inline void String::set_str(const char* value) {
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nfsfuse.String.str)
}
inline void String::set_str(const char* value, size_t size) {
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nfsfuse.String.str)
}
inline ::std::string* String::mutable_str() {
  
  // @@protoc_insertion_point(field_mutable:nfsfuse.String.str)
  return str_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* String::release_str() {
  // @@protoc_insertion_point(field_release:nfsfuse.String.str)
  
  return str_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void String::set_allocated_str(::std::string* str) {
  if (str != NULL) {
    
  } else {
    
  }
  str_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), str);
  // @@protoc_insertion_point(field_set_allocated:nfsfuse.String.str)
}

// -------------------------------------------------------------------

// Dirent

// optional uint32 dino = 1;
inline void Dirent::clear_dino() {
  dino_ = 0u;
}
inline ::google::protobuf::uint32 Dirent::dino() const {
  // @@protoc_insertion_point(field_get:nfsfuse.Dirent.dino)
  return dino_;
}
inline void Dirent::set_dino(::google::protobuf::uint32 value) {
  
  dino_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.Dirent.dino)
}

// optional string dname = 2;
inline void Dirent::clear_dname() {
  dname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Dirent::dname() const {
  // @@protoc_insertion_point(field_get:nfsfuse.Dirent.dname)
  return dname_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Dirent::set_dname(const ::std::string& value) {
  
  dname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nfsfuse.Dirent.dname)
}
inline void Dirent::set_dname(const char* value) {
  
  dname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nfsfuse.Dirent.dname)
}
inline void Dirent::set_dname(const char* value, size_t size) {
  
  dname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nfsfuse.Dirent.dname)
}
inline ::std::string* Dirent::mutable_dname() {
  
  // @@protoc_insertion_point(field_mutable:nfsfuse.Dirent.dname)
  return dname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Dirent::release_dname() {
  // @@protoc_insertion_point(field_release:nfsfuse.Dirent.dname)
  
  return dname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Dirent::set_allocated_dname(::std::string* dname) {
  if (dname != NULL) {
    
  } else {
    
  }
  dname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), dname);
  // @@protoc_insertion_point(field_set_allocated:nfsfuse.Dirent.dname)
}

// optional uint32 dtype = 3;
inline void Dirent::clear_dtype() {
  dtype_ = 0u;
}
inline ::google::protobuf::uint32 Dirent::dtype() const {
  // @@protoc_insertion_point(field_get:nfsfuse.Dirent.dtype)
  return dtype_;
}
inline void Dirent::set_dtype(::google::protobuf::uint32 value) {
  
  dtype_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.Dirent.dtype)
}

// optional uint32 err = 4;
inline void Dirent::clear_err() {
  err_ = 0u;
}
inline ::google::protobuf::uint32 Dirent::err() const {
  // @@protoc_insertion_point(field_get:nfsfuse.Dirent.err)
  return err_;
}
inline void Dirent::set_err(::google::protobuf::uint32 value) {
  
  err_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.Dirent.err)
}

// -------------------------------------------------------------------

// Stat

// optional uint32 dev = 1;
inline void Stat::clear_dev() {
  dev_ = 0u;
}
inline ::google::protobuf::uint32 Stat::dev() const {
  // @@protoc_insertion_point(field_get:nfsfuse.Stat.dev)
  return dev_;
}
inline void Stat::set_dev(::google::protobuf::uint32 value) {
  
  dev_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.Stat.dev)
}

// optional uint32 ino = 2;
inline void Stat::clear_ino() {
  ino_ = 0u;
}
inline ::google::protobuf::uint32 Stat::ino() const {
  // @@protoc_insertion_point(field_get:nfsfuse.Stat.ino)
  return ino_;
}
inline void Stat::set_ino(::google::protobuf::uint32 value) {
  
  ino_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.Stat.ino)
}

// optional uint32 mode = 3;
inline void Stat::clear_mode() {
  mode_ = 0u;
}
inline ::google::protobuf::uint32 Stat::mode() const {
  // @@protoc_insertion_point(field_get:nfsfuse.Stat.mode)
  return mode_;
}
inline void Stat::set_mode(::google::protobuf::uint32 value) {
  
  mode_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.Stat.mode)
}

// optional uint32 nlink = 4;
inline void Stat::clear_nlink() {
  nlink_ = 0u;
}
inline ::google::protobuf::uint32 Stat::nlink() const {
  // @@protoc_insertion_point(field_get:nfsfuse.Stat.nlink)
  return nlink_;
}
inline void Stat::set_nlink(::google::protobuf::uint32 value) {
  
  nlink_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.Stat.nlink)
}

// optional uint32 uid = 5;
inline void Stat::clear_uid() {
  uid_ = 0u;
}
inline ::google::protobuf::uint32 Stat::uid() const {
  // @@protoc_insertion_point(field_get:nfsfuse.Stat.uid)
  return uid_;
}
inline void Stat::set_uid(::google::protobuf::uint32 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.Stat.uid)
}

// optional uint32 gid = 6;
inline void Stat::clear_gid() {
  gid_ = 0u;
}
inline ::google::protobuf::uint32 Stat::gid() const {
  // @@protoc_insertion_point(field_get:nfsfuse.Stat.gid)
  return gid_;
}
inline void Stat::set_gid(::google::protobuf::uint32 value) {
  
  gid_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.Stat.gid)
}

// optional sint64 size = 7;
inline void Stat::clear_size() {
  size_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Stat::size() const {
  // @@protoc_insertion_point(field_get:nfsfuse.Stat.size)
  return size_;
}
inline void Stat::set_size(::google::protobuf::int64 value) {
  
  size_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.Stat.size)
}

// optional sint64 blksize = 8;
inline void Stat::clear_blksize() {
  blksize_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Stat::blksize() const {
  // @@protoc_insertion_point(field_get:nfsfuse.Stat.blksize)
  return blksize_;
}
inline void Stat::set_blksize(::google::protobuf::int64 value) {
  
  blksize_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.Stat.blksize)
}

// optional sint64 blocks = 9;
inline void Stat::clear_blocks() {
  blocks_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Stat::blocks() const {
  // @@protoc_insertion_point(field_get:nfsfuse.Stat.blocks)
  return blocks_;
}
inline void Stat::set_blocks(::google::protobuf::int64 value) {
  
  blocks_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.Stat.blocks)
}

// optional uint32 atime = 10;
inline void Stat::clear_atime() {
  atime_ = 0u;
}
inline ::google::protobuf::uint32 Stat::atime() const {
  // @@protoc_insertion_point(field_get:nfsfuse.Stat.atime)
  return atime_;
}
inline void Stat::set_atime(::google::protobuf::uint32 value) {
  
  atime_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.Stat.atime)
}

// optional uint32 mtime = 11;
inline void Stat::clear_mtime() {
  mtime_ = 0u;
}
inline ::google::protobuf::uint32 Stat::mtime() const {
  // @@protoc_insertion_point(field_get:nfsfuse.Stat.mtime)
  return mtime_;
}
inline void Stat::set_mtime(::google::protobuf::uint32 value) {
  
  mtime_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.Stat.mtime)
}

// optional uint32 ctime = 12;
inline void Stat::clear_ctime() {
  ctime_ = 0u;
}
inline ::google::protobuf::uint32 Stat::ctime() const {
  // @@protoc_insertion_point(field_get:nfsfuse.Stat.ctime)
  return ctime_;
}
inline void Stat::set_ctime(::google::protobuf::uint32 value) {
  
  ctime_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.Stat.ctime)
}

// optional uint32 err = 14;
inline void Stat::clear_err() {
  err_ = 0u;
}
inline ::google::protobuf::uint32 Stat::err() const {
  // @@protoc_insertion_point(field_get:nfsfuse.Stat.err)
  return err_;
}
inline void Stat::set_err(::google::protobuf::uint32 value) {
  
  err_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.Stat.err)
}

// -------------------------------------------------------------------

// FuseFileInfo

// optional int32 flags = 1;
inline void FuseFileInfo::clear_flags() {
  flags_ = 0;
}
inline ::google::protobuf::int32 FuseFileInfo::flags() const {
  // @@protoc_insertion_point(field_get:nfsfuse.FuseFileInfo.flags)
  return flags_;
}
inline void FuseFileInfo::set_flags(::google::protobuf::int32 value) {
  
  flags_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.FuseFileInfo.flags)
}

// optional int32 fh = 2;
inline void FuseFileInfo::clear_fh() {
  fh_ = 0;
}
inline ::google::protobuf::int32 FuseFileInfo::fh() const {
  // @@protoc_insertion_point(field_get:nfsfuse.FuseFileInfo.fh)
  return fh_;
}
inline void FuseFileInfo::set_fh(::google::protobuf::int32 value) {
  
  fh_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.FuseFileInfo.fh)
}

// optional uint32 oldfh = 3;
inline void FuseFileInfo::clear_oldfh() {
  oldfh_ = 0u;
}
inline ::google::protobuf::uint32 FuseFileInfo::oldfh() const {
  // @@protoc_insertion_point(field_get:nfsfuse.FuseFileInfo.oldfh)
  return oldfh_;
}
inline void FuseFileInfo::set_oldfh(::google::protobuf::uint32 value) {
  
  oldfh_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.FuseFileInfo.oldfh)
}

// optional uint64 lockowner = 5;
inline void FuseFileInfo::clear_lockowner() {
  lockowner_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 FuseFileInfo::lockowner() const {
  // @@protoc_insertion_point(field_get:nfsfuse.FuseFileInfo.lockowner)
  return lockowner_;
}
inline void FuseFileInfo::set_lockowner(::google::protobuf::uint64 value) {
  
  lockowner_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.FuseFileInfo.lockowner)
}

// optional uint32 pollevent = 6;
inline void FuseFileInfo::clear_pollevent() {
  pollevent_ = 0u;
}
inline ::google::protobuf::uint32 FuseFileInfo::pollevent() const {
  // @@protoc_insertion_point(field_get:nfsfuse.FuseFileInfo.pollevent)
  return pollevent_;
}
inline void FuseFileInfo::set_pollevent(::google::protobuf::uint32 value) {
  
  pollevent_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.FuseFileInfo.pollevent)
}

// optional uint32 err = 4;
inline void FuseFileInfo::clear_err() {
  err_ = 0u;
}
inline ::google::protobuf::uint32 FuseFileInfo::err() const {
  // @@protoc_insertion_point(field_get:nfsfuse.FuseFileInfo.err)
  return err_;
}
inline void FuseFileInfo::set_err(::google::protobuf::uint32 value) {
  
  err_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.FuseFileInfo.err)
}

// optional string path = 7;
inline void FuseFileInfo::clear_path() {
  path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FuseFileInfo::path() const {
  // @@protoc_insertion_point(field_get:nfsfuse.FuseFileInfo.path)
  return path_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FuseFileInfo::set_path(const ::std::string& value) {
  
  path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nfsfuse.FuseFileInfo.path)
}
inline void FuseFileInfo::set_path(const char* value) {
  
  path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nfsfuse.FuseFileInfo.path)
}
inline void FuseFileInfo::set_path(const char* value, size_t size) {
  
  path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nfsfuse.FuseFileInfo.path)
}
inline ::std::string* FuseFileInfo::mutable_path() {
  
  // @@protoc_insertion_point(field_mutable:nfsfuse.FuseFileInfo.path)
  return path_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FuseFileInfo::release_path() {
  // @@protoc_insertion_point(field_release:nfsfuse.FuseFileInfo.path)
  
  return path_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FuseFileInfo::set_allocated_path(::std::string* path) {
  if (path != NULL) {
    
  } else {
    
  }
  path_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), path);
  // @@protoc_insertion_point(field_set_allocated:nfsfuse.FuseFileInfo.path)
}

// -------------------------------------------------------------------

// ReadResult

// optional int32 bytesread = 1;
inline void ReadResult::clear_bytesread() {
  bytesread_ = 0;
}
inline ::google::protobuf::int32 ReadResult::bytesread() const {
  // @@protoc_insertion_point(field_get:nfsfuse.ReadResult.bytesread)
  return bytesread_;
}
inline void ReadResult::set_bytesread(::google::protobuf::int32 value) {
  
  bytesread_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.ReadResult.bytesread)
}

// optional bytes buffer = 2;
inline void ReadResult::clear_buffer() {
  buffer_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ReadResult::buffer() const {
  // @@protoc_insertion_point(field_get:nfsfuse.ReadResult.buffer)
  return buffer_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReadResult::set_buffer(const ::std::string& value) {
  
  buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nfsfuse.ReadResult.buffer)
}
inline void ReadResult::set_buffer(const char* value) {
  
  buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nfsfuse.ReadResult.buffer)
}
inline void ReadResult::set_buffer(const void* value, size_t size) {
  
  buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nfsfuse.ReadResult.buffer)
}
inline ::std::string* ReadResult::mutable_buffer() {
  
  // @@protoc_insertion_point(field_mutable:nfsfuse.ReadResult.buffer)
  return buffer_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ReadResult::release_buffer() {
  // @@protoc_insertion_point(field_release:nfsfuse.ReadResult.buffer)
  
  return buffer_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReadResult::set_allocated_buffer(::std::string* buffer) {
  if (buffer != NULL) {
    
  } else {
    
  }
  buffer_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), buffer);
  // @@protoc_insertion_point(field_set_allocated:nfsfuse.ReadResult.buffer)
}

// -------------------------------------------------------------------

// ReadRequest

// optional string path = 1;
inline void ReadRequest::clear_path() {
  path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ReadRequest::path() const {
  // @@protoc_insertion_point(field_get:nfsfuse.ReadRequest.path)
  return path_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReadRequest::set_path(const ::std::string& value) {
  
  path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nfsfuse.ReadRequest.path)
}
inline void ReadRequest::set_path(const char* value) {
  
  path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nfsfuse.ReadRequest.path)
}
inline void ReadRequest::set_path(const char* value, size_t size) {
  
  path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nfsfuse.ReadRequest.path)
}
inline ::std::string* ReadRequest::mutable_path() {
  
  // @@protoc_insertion_point(field_mutable:nfsfuse.ReadRequest.path)
  return path_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ReadRequest::release_path() {
  // @@protoc_insertion_point(field_release:nfsfuse.ReadRequest.path)
  
  return path_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReadRequest::set_allocated_path(::std::string* path) {
  if (path != NULL) {
    
  } else {
    
  }
  path_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), path);
  // @@protoc_insertion_point(field_set_allocated:nfsfuse.ReadRequest.path)
}

// optional uint32 size = 2;
inline void ReadRequest::clear_size() {
  size_ = 0u;
}
inline ::google::protobuf::uint32 ReadRequest::size() const {
  // @@protoc_insertion_point(field_get:nfsfuse.ReadRequest.size)
  return size_;
}
inline void ReadRequest::set_size(::google::protobuf::uint32 value) {
  
  size_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.ReadRequest.size)
}

// optional int64 offset = 3;
inline void ReadRequest::clear_offset() {
  offset_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 ReadRequest::offset() const {
  // @@protoc_insertion_point(field_get:nfsfuse.ReadRequest.offset)
  return offset_;
}
inline void ReadRequest::set_offset(::google::protobuf::int64 value) {
  
  offset_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.ReadRequest.offset)
}

// -------------------------------------------------------------------

// WriteRequest

// optional string path = 1;
inline void WriteRequest::clear_path() {
  path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& WriteRequest::path() const {
  // @@protoc_insertion_point(field_get:nfsfuse.WriteRequest.path)
  return path_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WriteRequest::set_path(const ::std::string& value) {
  
  path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nfsfuse.WriteRequest.path)
}
inline void WriteRequest::set_path(const char* value) {
  
  path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nfsfuse.WriteRequest.path)
}
inline void WriteRequest::set_path(const char* value, size_t size) {
  
  path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nfsfuse.WriteRequest.path)
}
inline ::std::string* WriteRequest::mutable_path() {
  
  // @@protoc_insertion_point(field_mutable:nfsfuse.WriteRequest.path)
  return path_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* WriteRequest::release_path() {
  // @@protoc_insertion_point(field_release:nfsfuse.WriteRequest.path)
  
  return path_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WriteRequest::set_allocated_path(::std::string* path) {
  if (path != NULL) {
    
  } else {
    
  }
  path_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), path);
  // @@protoc_insertion_point(field_set_allocated:nfsfuse.WriteRequest.path)
}

// optional uint32 size = 2;
inline void WriteRequest::clear_size() {
  size_ = 0u;
}
inline ::google::protobuf::uint32 WriteRequest::size() const {
  // @@protoc_insertion_point(field_get:nfsfuse.WriteRequest.size)
  return size_;
}
inline void WriteRequest::set_size(::google::protobuf::uint32 value) {
  
  size_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.WriteRequest.size)
}

// optional int32 offset = 3;
inline void WriteRequest::clear_offset() {
  offset_ = 0;
}
inline ::google::protobuf::int32 WriteRequest::offset() const {
  // @@protoc_insertion_point(field_get:nfsfuse.WriteRequest.offset)
  return offset_;
}
inline void WriteRequest::set_offset(::google::protobuf::int32 value) {
  
  offset_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.WriteRequest.offset)
}

// optional bytes buffer = 4;
inline void WriteRequest::clear_buffer() {
  buffer_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& WriteRequest::buffer() const {
  // @@protoc_insertion_point(field_get:nfsfuse.WriteRequest.buffer)
  return buffer_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WriteRequest::set_buffer(const ::std::string& value) {
  
  buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nfsfuse.WriteRequest.buffer)
}
inline void WriteRequest::set_buffer(const char* value) {
  
  buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nfsfuse.WriteRequest.buffer)
}
inline void WriteRequest::set_buffer(const void* value, size_t size) {
  
  buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nfsfuse.WriteRequest.buffer)
}
inline ::std::string* WriteRequest::mutable_buffer() {
  
  // @@protoc_insertion_point(field_mutable:nfsfuse.WriteRequest.buffer)
  return buffer_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* WriteRequest::release_buffer() {
  // @@protoc_insertion_point(field_release:nfsfuse.WriteRequest.buffer)
  
  return buffer_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WriteRequest::set_allocated_buffer(::std::string* buffer) {
  if (buffer != NULL) {
    
  } else {
    
  }
  buffer_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), buffer);
  // @@protoc_insertion_point(field_set_allocated:nfsfuse.WriteRequest.buffer)
}

// -------------------------------------------------------------------

// WriteResult

// optional int32 nbytes = 1;
inline void WriteResult::clear_nbytes() {
  nbytes_ = 0;
}
inline ::google::protobuf::int32 WriteResult::nbytes() const {
  // @@protoc_insertion_point(field_get:nfsfuse.WriteResult.nbytes)
  return nbytes_;
}
inline void WriteResult::set_nbytes(::google::protobuf::int32 value) {
  
  nbytes_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.WriteResult.nbytes)
}

// optional int32 err = 2;
inline void WriteResult::clear_err() {
  err_ = 0;
}
inline ::google::protobuf::int32 WriteResult::err() const {
  // @@protoc_insertion_point(field_get:nfsfuse.WriteResult.err)
  return err_;
}
inline void WriteResult::set_err(::google::protobuf::int32 value) {
  
  err_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.WriteResult.err)
}

// -------------------------------------------------------------------

// Mkdir

// optional string s = 1;
inline void Mkdir::clear_s() {
  s_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Mkdir::s() const {
  // @@protoc_insertion_point(field_get:nfsfuse.Mkdir.s)
  return s_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Mkdir::set_s(const ::std::string& value) {
  
  s_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nfsfuse.Mkdir.s)
}
inline void Mkdir::set_s(const char* value) {
  
  s_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nfsfuse.Mkdir.s)
}
inline void Mkdir::set_s(const char* value, size_t size) {
  
  s_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nfsfuse.Mkdir.s)
}
inline ::std::string* Mkdir::mutable_s() {
  
  // @@protoc_insertion_point(field_mutable:nfsfuse.Mkdir.s)
  return s_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Mkdir::release_s() {
  // @@protoc_insertion_point(field_release:nfsfuse.Mkdir.s)
  
  return s_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Mkdir::set_allocated_s(::std::string* s) {
  if (s != NULL) {
    
  } else {
    
  }
  s_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), s);
  // @@protoc_insertion_point(field_set_allocated:nfsfuse.Mkdir.s)
}

// optional uint32 mode = 2;
inline void Mkdir::clear_mode() {
  mode_ = 0u;
}
inline ::google::protobuf::uint32 Mkdir::mode() const {
  // @@protoc_insertion_point(field_get:nfsfuse.Mkdir.mode)
  return mode_;
}
inline void Mkdir::set_mode(::google::protobuf::uint32 value) {
  
  mode_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.Mkdir.mode)
}

// -------------------------------------------------------------------

// MkdirOutput

// optional string str = 1;
inline void MkdirOutput::clear_str() {
  str_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MkdirOutput::str() const {
  // @@protoc_insertion_point(field_get:nfsfuse.MkdirOutput.str)
  return str_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MkdirOutput::set_str(const ::std::string& value) {
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nfsfuse.MkdirOutput.str)
}
inline void MkdirOutput::set_str(const char* value) {
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nfsfuse.MkdirOutput.str)
}
inline void MkdirOutput::set_str(const char* value, size_t size) {
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nfsfuse.MkdirOutput.str)
}
inline ::std::string* MkdirOutput::mutable_str() {
  
  // @@protoc_insertion_point(field_mutable:nfsfuse.MkdirOutput.str)
  return str_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MkdirOutput::release_str() {
  // @@protoc_insertion_point(field_release:nfsfuse.MkdirOutput.str)
  
  return str_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MkdirOutput::set_allocated_str(::std::string* str) {
  if (str != NULL) {
    
  } else {
    
  }
  str_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), str);
  // @@protoc_insertion_point(field_set_allocated:nfsfuse.MkdirOutput.str)
}

// optional uint32 err = 2;
inline void MkdirOutput::clear_err() {
  err_ = 0u;
}
inline ::google::protobuf::uint32 MkdirOutput::err() const {
  // @@protoc_insertion_point(field_get:nfsfuse.MkdirOutput.err)
  return err_;
}
inline void MkdirOutput::set_err(::google::protobuf::uint32 value) {
  
  err_ = value;
  // @@protoc_insertion_point(field_set:nfsfuse.MkdirOutput.err)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace nfsfuse

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_nfsfuse_2eproto__INCLUDED
