// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: nfsfuse.proto

#include "nfsfuse.pb.h"
#include "nfsfuse.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>
namespace nfsfuse {

static const char* NFS_method_names[] = {
  "/nfsfuse.NFS/nfsfuse_getattr",
  "/nfsfuse.NFS/nfsfuse_readdir",
  "/nfsfuse.NFS/nfsfuse_open",
  "/nfsfuse.NFS/nfsfuse_read",
  "/nfsfuse.NFS/nfsfuse_write",
  "/nfsfuse.NFS/nfsfuse_create",
  "/nfsfuse.NFS/nfsfuse_mkdir",
  "/nfsfuse.NFS/nfsfuse_rmdir",
  "/nfsfuse.NFS/nfsfuse_unlink",
  "/nfsfuse.NFS/nfsfuse_rename",
  "/nfsfuse.NFS/nfsfuse_utimens",
  "/nfsfuse.NFS/nfsfuse_mknod",
  "/nfsfuse.NFS/nfsfuse_release",
  "/nfsfuse.NFS/nfsfuse_flush",
};

std::unique_ptr< NFS::Stub> NFS::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  std::unique_ptr< NFS::Stub> stub(new NFS::Stub(channel));
  return stub;
}

NFS::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_nfsfuse_getattr_(NFS_method_names[0], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_nfsfuse_readdir_(NFS_method_names[1], ::grpc::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_nfsfuse_open_(NFS_method_names[2], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_nfsfuse_read_(NFS_method_names[3], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_nfsfuse_write_(NFS_method_names[4], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_nfsfuse_create_(NFS_method_names[5], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_nfsfuse_mkdir_(NFS_method_names[6], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_nfsfuse_rmdir_(NFS_method_names[7], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_nfsfuse_unlink_(NFS_method_names[8], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_nfsfuse_rename_(NFS_method_names[9], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_nfsfuse_utimens_(NFS_method_names[10], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_nfsfuse_mknod_(NFS_method_names[11], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_nfsfuse_release_(NFS_method_names[12], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_nfsfuse_flush_(NFS_method_names[13], ::grpc::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status NFS::Stub::nfsfuse_getattr(::grpc::ClientContext* context, const ::nfsfuse::String& request, ::nfsfuse::Stat* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_nfsfuse_getattr_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::nfsfuse::Stat>* NFS::Stub::Asyncnfsfuse_getattrRaw(::grpc::ClientContext* context, const ::nfsfuse::String& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::nfsfuse::Stat>(channel_.get(), cq, rpcmethod_nfsfuse_getattr_, context, request);
}

::grpc::ClientReader< ::nfsfuse::Dirent>* NFS::Stub::nfsfuse_readdirRaw(::grpc::ClientContext* context, const ::nfsfuse::String& request) {
  return new ::grpc::ClientReader< ::nfsfuse::Dirent>(channel_.get(), rpcmethod_nfsfuse_readdir_, context, request);
}

::grpc::ClientAsyncReader< ::nfsfuse::Dirent>* NFS::Stub::Asyncnfsfuse_readdirRaw(::grpc::ClientContext* context, const ::nfsfuse::String& request, ::grpc::CompletionQueue* cq, void* tag) {
  return new ::grpc::ClientAsyncReader< ::nfsfuse::Dirent>(channel_.get(), cq, rpcmethod_nfsfuse_readdir_, context, request, tag);
}

::grpc::Status NFS::Stub::nfsfuse_open(::grpc::ClientContext* context, const ::nfsfuse::FuseFileInfo& request, ::nfsfuse::FuseFileInfo* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_nfsfuse_open_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::nfsfuse::FuseFileInfo>* NFS::Stub::Asyncnfsfuse_openRaw(::grpc::ClientContext* context, const ::nfsfuse::FuseFileInfo& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::nfsfuse::FuseFileInfo>(channel_.get(), cq, rpcmethod_nfsfuse_open_, context, request);
}

::grpc::Status NFS::Stub::nfsfuse_read(::grpc::ClientContext* context, const ::nfsfuse::ReadRequest& request, ::nfsfuse::ReadResult* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_nfsfuse_read_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::nfsfuse::ReadResult>* NFS::Stub::Asyncnfsfuse_readRaw(::grpc::ClientContext* context, const ::nfsfuse::ReadRequest& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::nfsfuse::ReadResult>(channel_.get(), cq, rpcmethod_nfsfuse_read_, context, request);
}

::grpc::Status NFS::Stub::nfsfuse_write(::grpc::ClientContext* context, const ::nfsfuse::WriteRequest& request, ::nfsfuse::WriteResult* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_nfsfuse_write_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::nfsfuse::WriteResult>* NFS::Stub::Asyncnfsfuse_writeRaw(::grpc::ClientContext* context, const ::nfsfuse::WriteRequest& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::nfsfuse::WriteResult>(channel_.get(), cq, rpcmethod_nfsfuse_write_, context, request);
}

::grpc::Status NFS::Stub::nfsfuse_create(::grpc::ClientContext* context, const ::nfsfuse::CreateRequest& request, ::nfsfuse::CreateResult* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_nfsfuse_create_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::nfsfuse::CreateResult>* NFS::Stub::Asyncnfsfuse_createRaw(::grpc::ClientContext* context, const ::nfsfuse::CreateRequest& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::nfsfuse::CreateResult>(channel_.get(), cq, rpcmethod_nfsfuse_create_, context, request);
}

::grpc::Status NFS::Stub::nfsfuse_mkdir(::grpc::ClientContext* context, const ::nfsfuse::MkdirRequest& request, ::nfsfuse::OutputInfo* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_nfsfuse_mkdir_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::nfsfuse::OutputInfo>* NFS::Stub::Asyncnfsfuse_mkdirRaw(::grpc::ClientContext* context, const ::nfsfuse::MkdirRequest& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::nfsfuse::OutputInfo>(channel_.get(), cq, rpcmethod_nfsfuse_mkdir_, context, request);
}

::grpc::Status NFS::Stub::nfsfuse_rmdir(::grpc::ClientContext* context, const ::nfsfuse::String& request, ::nfsfuse::OutputInfo* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_nfsfuse_rmdir_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::nfsfuse::OutputInfo>* NFS::Stub::Asyncnfsfuse_rmdirRaw(::grpc::ClientContext* context, const ::nfsfuse::String& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::nfsfuse::OutputInfo>(channel_.get(), cq, rpcmethod_nfsfuse_rmdir_, context, request);
}

::grpc::Status NFS::Stub::nfsfuse_unlink(::grpc::ClientContext* context, const ::nfsfuse::String& request, ::nfsfuse::OutputInfo* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_nfsfuse_unlink_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::nfsfuse::OutputInfo>* NFS::Stub::Asyncnfsfuse_unlinkRaw(::grpc::ClientContext* context, const ::nfsfuse::String& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::nfsfuse::OutputInfo>(channel_.get(), cq, rpcmethod_nfsfuse_unlink_, context, request);
}

::grpc::Status NFS::Stub::nfsfuse_rename(::grpc::ClientContext* context, const ::nfsfuse::RenameRequest& request, ::nfsfuse::OutputInfo* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_nfsfuse_rename_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::nfsfuse::OutputInfo>* NFS::Stub::Asyncnfsfuse_renameRaw(::grpc::ClientContext* context, const ::nfsfuse::RenameRequest& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::nfsfuse::OutputInfo>(channel_.get(), cq, rpcmethod_nfsfuse_rename_, context, request);
}

::grpc::Status NFS::Stub::nfsfuse_utimens(::grpc::ClientContext* context, const ::nfsfuse::UtimensRequest& request, ::nfsfuse::OutputInfo* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_nfsfuse_utimens_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::nfsfuse::OutputInfo>* NFS::Stub::Asyncnfsfuse_utimensRaw(::grpc::ClientContext* context, const ::nfsfuse::UtimensRequest& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::nfsfuse::OutputInfo>(channel_.get(), cq, rpcmethod_nfsfuse_utimens_, context, request);
}

::grpc::Status NFS::Stub::nfsfuse_mknod(::grpc::ClientContext* context, const ::nfsfuse::MknodRequest& request, ::nfsfuse::OutputInfo* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_nfsfuse_mknod_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::nfsfuse::OutputInfo>* NFS::Stub::Asyncnfsfuse_mknodRaw(::grpc::ClientContext* context, const ::nfsfuse::MknodRequest& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::nfsfuse::OutputInfo>(channel_.get(), cq, rpcmethod_nfsfuse_mknod_, context, request);
}

::grpc::Status NFS::Stub::nfsfuse_release(::grpc::ClientContext* context, const ::nfsfuse::FileDesc& request, ::nfsfuse::Errno* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_nfsfuse_release_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::nfsfuse::Errno>* NFS::Stub::Asyncnfsfuse_releaseRaw(::grpc::ClientContext* context, const ::nfsfuse::FileDesc& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::nfsfuse::Errno>(channel_.get(), cq, rpcmethod_nfsfuse_release_, context, request);
}

::grpc::Status NFS::Stub::nfsfuse_flush(::grpc::ClientContext* context, const ::nfsfuse::FileDesc& request, ::nfsfuse::Errno* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_nfsfuse_flush_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::nfsfuse::Errno>* NFS::Stub::Asyncnfsfuse_flushRaw(::grpc::ClientContext* context, const ::nfsfuse::FileDesc& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::nfsfuse::Errno>(channel_.get(), cq, rpcmethod_nfsfuse_flush_, context, request);
}

NFS::Service::Service() {
  (void)NFS_method_names;
  AddMethod(new ::grpc::RpcServiceMethod(
      NFS_method_names[0],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< NFS::Service, ::nfsfuse::String, ::nfsfuse::Stat>(
          std::mem_fn(&NFS::Service::nfsfuse_getattr), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      NFS_method_names[1],
      ::grpc::RpcMethod::SERVER_STREAMING,
      new ::grpc::ServerStreamingHandler< NFS::Service, ::nfsfuse::String, ::nfsfuse::Dirent>(
          std::mem_fn(&NFS::Service::nfsfuse_readdir), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      NFS_method_names[2],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< NFS::Service, ::nfsfuse::FuseFileInfo, ::nfsfuse::FuseFileInfo>(
          std::mem_fn(&NFS::Service::nfsfuse_open), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      NFS_method_names[3],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< NFS::Service, ::nfsfuse::ReadRequest, ::nfsfuse::ReadResult>(
          std::mem_fn(&NFS::Service::nfsfuse_read), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      NFS_method_names[4],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< NFS::Service, ::nfsfuse::WriteRequest, ::nfsfuse::WriteResult>(
          std::mem_fn(&NFS::Service::nfsfuse_write), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      NFS_method_names[5],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< NFS::Service, ::nfsfuse::CreateRequest, ::nfsfuse::CreateResult>(
          std::mem_fn(&NFS::Service::nfsfuse_create), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      NFS_method_names[6],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< NFS::Service, ::nfsfuse::MkdirRequest, ::nfsfuse::OutputInfo>(
          std::mem_fn(&NFS::Service::nfsfuse_mkdir), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      NFS_method_names[7],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< NFS::Service, ::nfsfuse::String, ::nfsfuse::OutputInfo>(
          std::mem_fn(&NFS::Service::nfsfuse_rmdir), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      NFS_method_names[8],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< NFS::Service, ::nfsfuse::String, ::nfsfuse::OutputInfo>(
          std::mem_fn(&NFS::Service::nfsfuse_unlink), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      NFS_method_names[9],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< NFS::Service, ::nfsfuse::RenameRequest, ::nfsfuse::OutputInfo>(
          std::mem_fn(&NFS::Service::nfsfuse_rename), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      NFS_method_names[10],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< NFS::Service, ::nfsfuse::UtimensRequest, ::nfsfuse::OutputInfo>(
          std::mem_fn(&NFS::Service::nfsfuse_utimens), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      NFS_method_names[11],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< NFS::Service, ::nfsfuse::MknodRequest, ::nfsfuse::OutputInfo>(
          std::mem_fn(&NFS::Service::nfsfuse_mknod), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      NFS_method_names[12],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< NFS::Service, ::nfsfuse::FileDesc, ::nfsfuse::Errno>(
          std::mem_fn(&NFS::Service::nfsfuse_release), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      NFS_method_names[13],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< NFS::Service, ::nfsfuse::FileDesc, ::nfsfuse::Errno>(
          std::mem_fn(&NFS::Service::nfsfuse_flush), this)));
}

NFS::Service::~Service() {
}

::grpc::Status NFS::Service::nfsfuse_getattr(::grpc::ServerContext* context, const ::nfsfuse::String* request, ::nfsfuse::Stat* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NFS::Service::nfsfuse_readdir(::grpc::ServerContext* context, const ::nfsfuse::String* request, ::grpc::ServerWriter< ::nfsfuse::Dirent>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NFS::Service::nfsfuse_open(::grpc::ServerContext* context, const ::nfsfuse::FuseFileInfo* request, ::nfsfuse::FuseFileInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NFS::Service::nfsfuse_read(::grpc::ServerContext* context, const ::nfsfuse::ReadRequest* request, ::nfsfuse::ReadResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NFS::Service::nfsfuse_write(::grpc::ServerContext* context, const ::nfsfuse::WriteRequest* request, ::nfsfuse::WriteResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NFS::Service::nfsfuse_create(::grpc::ServerContext* context, const ::nfsfuse::CreateRequest* request, ::nfsfuse::CreateResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NFS::Service::nfsfuse_mkdir(::grpc::ServerContext* context, const ::nfsfuse::MkdirRequest* request, ::nfsfuse::OutputInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NFS::Service::nfsfuse_rmdir(::grpc::ServerContext* context, const ::nfsfuse::String* request, ::nfsfuse::OutputInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NFS::Service::nfsfuse_unlink(::grpc::ServerContext* context, const ::nfsfuse::String* request, ::nfsfuse::OutputInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NFS::Service::nfsfuse_rename(::grpc::ServerContext* context, const ::nfsfuse::RenameRequest* request, ::nfsfuse::OutputInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NFS::Service::nfsfuse_utimens(::grpc::ServerContext* context, const ::nfsfuse::UtimensRequest* request, ::nfsfuse::OutputInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NFS::Service::nfsfuse_mknod(::grpc::ServerContext* context, const ::nfsfuse::MknodRequest* request, ::nfsfuse::OutputInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NFS::Service::nfsfuse_release(::grpc::ServerContext* context, const ::nfsfuse::FileDesc* request, ::nfsfuse::Errno* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NFS::Service::nfsfuse_flush(::grpc::ServerContext* context, const ::nfsfuse::FileDesc* request, ::nfsfuse::Errno* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace nfsfuse

